# Starship configuration     https://starship.rs/config/
# Nerd font icons (useful)   https://www.nerdfonts.com/cheat-sheet

format = """
($cmd_duration)\
$character"""

[character]
success_symbol = '[󰪥](blue)'
error_symbol = '[](red)'
vimcmd_symbol = '[⊽](blue)'

[cmd_duration]  # https://starship.rs/config/#command-duration
format = '[$duration ](yellow)'
min_time = 2000
