# Starship configuration     https://starship.rs/config/
# Nerd font icons (useful)   https://www.nerdfonts.com/cheat-sheet

format = """
[](color_true_black)$os\
[](fg:color_true_black bg:color_true_white)$cmd_duration\
[ ](fg:color_true_black bg:color_true_white)$directory[](bg:color_true_white)\
[](fg:color_true_white bg:color_true_black)\
[ ](bg:color_true_black)$git_branch\
[ ](fg:color_true_white bg:color_true_black)\
($python$nodejs[ ](bg:color_true_black))\
$character\
"""

right_format = """
($memory_usage )\
($time )\
"""

palette = 'colors'

[palettes.colors]
color_black         = 'black'
color_bright_black  = 'bright-black'
color_true_white    = '#ffffff'
color_white         = 'white'
color_bright_white  = 'bright-white'
color_true_black    = '#000000'



#######################
##### Left Prompt #####
#######################

[os]
disabled = false
style = "fg:color_true_white bg:color_true_black"

[os.symbols]
Macos = " "
Linux = "󰌽 "
Windows = " "

[cmd_duration]  # https://starship.rs/config/#command-duration
format = '([ ](fg:color_true_black bg:color_true_white)[$duration]($style))'
style = 'fg:color_true_black bg:color_true_white'
show_milliseconds = true
min_time = 500

[directory]
style = "fg:color_true_black bg:color_true_white"
format = "[$path]($style)"
truncation_length = 2
truncation_symbol = '…/'

[git_branch]
symbol = ""
style = "fg:color_true_white bg:color_true_black"
format = '[$symbol $branch]($style)'

[python]
format = '[${pyenv_prefix}\((${virtualenv} )($version\))]($style)'
version_format = '${raw}'
style = "fg:color_true_white fg:color_true_black"
python_binary = ['python3', 'python']

[nodejs]
format = '[$symbol( $version)]($style)'
style = "fg:color_true_white bg:color_true_black"
symbol = ''
version_format = '${raw}'

[lua]
format = '[󰢱 $version]($style)'
style = 'fg:color_true_white bg:color_true_black'

[character]
success_symbol = "[](bg:color_true_black fg:color_true_white)[](bg:color_true_white fg:color_true_black)[](fg:color_true_white)"
error_symbol = "[](bg:color_true_black fg:color_true_white)[󱈸](bg:color_true_white fg:color_true_black)[](fg:color_true_white)"
vimcmd_symbol = "[](bg:color_true_black fg:color_true_white)[](bg:color_true_white fg:color_true_black)[](fg:color_true_white)"

# ------------------------------------------------------------------------



########################
##### Right Prompt #####
########################

[memory_usage]  # https://starship.rs/config/#memory-usage
format = '[](color_true_black)[$symbol ${ram_pct}( | ${swap_pct})]($style)[](color_true_black)'
disabled = false
threshold = -1
symbol = "󰧑"
style = 'bg:color_true_black fg:color_true_white'

[time]  # https://starship.rs/config/#time
disabled = false
time_format = "%I:%M%P"
style = "bg:color_true_white fg:color_true_black"
format = '[](color_true_white)[ $time]($style)[](color_true_white)'
