format = """
[](color_bg1)\
$directory\
[](fg:color_bg1 bg:color_bg2)\
$git_branch\
$git_status\
[](fg:color_bg2 bg:color_bg3)\
$python\
$nodejs\
$character\
"""

continuation_prompt = """
[](color_bg1)\
[ ](fg:color_yellow bg:color_bg1)\
[](fg:color_bg1 bg:color_bg2)\
[](fg:color_bg2 bg:color_bg3)\
[](fg:color_bg3 bg:color_yellow)\
[ ](fg:color_yellow)\
"""

right_format = """
($cmd_duration[ ](fg:color_fg0))\
($docker_context[ ](fg:color_fg0))\
($jobs[ ](fg:color_fg0))\
($memory_usage[ ](fg:color_fg0))\
($time[ ](fg:color_fg0))\
"""

palette = 'gh_dark'

[palettes.gh_dark]
color_fg0    = '#cdd9e5'
color_bg1    = '#373e47'
color_bg2    = '#545d68'
color_bg3    = '#768390'
color_blue   = 'blue'
color_aqua   = 'cyan'
color_green  = 'green'
color_orange = '#e0823d'
color_purple = 'magenta'
color_red    = 'red'
color_yellow = 'yellow'
color_pink   = '#e275ad'



##############
### Prompt ###
##############

[character]
success_symbol = "[](fg:color_bg3 bg:color_blue)[](fg:color_blue)"
error_symbol =   "[](fg:color_bg3 bg:color_red)[](fg:color_red)"
vimcmd_symbol =  "[](fg:color_bg3 bg:color_green)[](fg:color_green)"

[os]
disabled = false
style = "fg:color_fg0"

[os.symbols]
Windows = "󰍲"
Macos = "󰀵"
Linux = "󰌽"
Android = ""

[directory]
style = "bg:color_bg1 fg:color_fg0"
format = "[$path ]($style)"
truncation_length = 3
truncation_symbol = '…/'
# truncate_to_repo = false
# read_only = " 🔒"
# read_only_style = "bg:color_bg1 fg:color_fg0"
# before_repo_root_style = "bg:color_bg1 fg:color_fg0"
# repo_root_style = "bg:color_bg1 fg:color_fg0"



###########
### Git ###
###########

[git_branch]
symbol = ""
style = "bg:color_bg2 fg:color_fg0"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:color_bg2 fg:color_fg0"
format = "[(*$conflicted$untracked$modified$staged$renamed$deleted )($ahead_behind$stashed )]($style)"
conflicted = " \b"
untracked  = " \b"
modified   = " \b"
staged     = " \b"
renamed    = " \b"
deleted    = " \b"
stashed    = "≡"



#################
### Languages ###
#################

[python]
format = '[${pyenv_prefix}\((${virtualenv} )($version\) )]($style)'
version_format = '${raw}'
style = "fg:color_fg0 bg:color_bg1"
python_binary = ['python3', 'python']
detect_extensions = []
detect_folders = []

[nodejs]
format = '[ $symbol( $version) ]($style)'
style = "fg:color_fg0 bg:color_bg3"
symbol = ''
version_format = '${raw}'
detect_extensions = []

[lua]
format = ' [󰢱 $version]($style) '
style = 'fg:color_fg0 bg:color_bg3'


#############
### Shell ###
#############

[shell]  # https://starship.rs/config/#shell
style = 'fg:color_fg0 bg:color_bg2'
disabled = true

[status]  # https://starship.rs/config/#status
style = 'fg:color_fg0 bg:color_bg2'
disabled = true


#############
### Tools ###
#############

[jobs]  # https://starship.rs/config/#jobs
symbol = '+'
number_threshold = 2  # Show the number of jobs if the job count is at least number_threshold.
symbol_threshold = 4  # Show symbol if the job count is at least symbol_threshold.
style = 'fg:color_fg0 bg:color_bg2'
format = '[](color_bg2)[$symbol$number]($style)[](color_bg2)'

[memory_usage]  # https://starship.rs/config/#memory-usage
format = '[](color_bg2)[$symbol ${ram_pct}( | ${swap_pct})]($style)[](color_bg2)'
disabled = false
threshold = -1
symbol = "󰧑"
style = 'bg:color_bg2 fg:color_fg0'

[time]  # https://starship.rs/config/#time
disabled = false
time_format = "%I:%M%P"
style = "bg:color_bg2 fg:color_fg0"
format = '[](color_bg2)[ $time]($style)[](color_bg2)'

[cmd_duration]  # https://starship.rs/config/#command-duration
format = '[](color_bg2)[$duration]($style)[](color_bg2)'
style = 'fg:color_fg0 bg:color_bg2'
show_milliseconds = true
min_time = 0

[docker_context]  # https://starship.rs/config/#docker-context
format = '[](color_bg2)[ $context]($style)[](color_bg2)'
style = 'fg:color_fg0 bg:color_bg2'

