#!/bin/zsh

# Symlink from $HOME/.zshenv (target file).
export ZDOTDIR=$HOME/.config/zsh

# Zsh startup files: https://zsh.sourceforge.io/Intro/intro_3.html
# The `.zshenv` startup file is sourced on all invocations of the shell, unless the -f option is set.
# It should contain commands to set the command search path, plus other important environment variables.
# It should NOT contain commands that produce output or assume the shell is attached to a tty.

source "$HOME/.config/scripts/xdg.sh"  # Environment variables for XDG base directories
export SHELL_SESSIONS_DISABLE=1        # Disables .zsh_sessions folder created by Apple terminal

