# Starship configuration     https://starship.rs/config/
# Nerd font icons (useful)   https://www.nerdfonts.com/cheat-sheet

format = """
[](color_white)\
$os\
[ ](fg:color_black bg:color_white)\
[ ](fg:color_black bg:color_blue)\
$directory\
[ ](fg:color_black bg:color_blue)\
([ ](fg:color_black bg:color_red)\
$git_branch\
[ ](fg:color_black bg:color_red))\
([ ](fg:color_black bg:color_white)\
$python$nodejs\
[ ](fg:color_black bg:color_white))\
$character\
"""

right_format = """
($cmd_duration )\
($docker_context )\
($jobs )\
($memory_usage )\
($time )\
"""

palette = 'red_white_blue'

[palettes.red_white_blue]
color_black         = 'black'
color_bright_black  = 'bright-black'
color_red           = 'red'
color_bright_red    = 'bright-red'
color_blue          = 'blue'
color_bright_blue   = 'bright-blue'
color_white         = 'white'
color_bright_white  = 'bright-white'



#######################
##### Left Prompt #####
#######################

[os]
disabled = false
style = "bg:color_white fg:color_black"

[os.symbols]
Macos = ""
Linux = "󰌽"
Windows = ""

[directory]
style = "fg:color_bright_white bg:color_blue"
format = "[$path]($style)"
truncation_length = 3
truncation_symbol = '…/'

[git_branch]
symbol = ""
style = "fg:color_bright_white bg:color_red"
format = '[$symbol $branch]($style)'

[python]
format = '[${pyenv_prefix}\((${virtualenv} )($version\))]($style)'
version_format = '${raw}'
style = "fg:color_black fg:color_white"
python_binary = ['python3', 'python']

[nodejs]
format = '[$symbol( $version)]($style)'
style = "fg:color_black bg:color_white"
symbol = ''
version_format = '${raw}'

[character]
success_symbol = "[ ](fg:color_black bg:color_blue)[❯](bg:color_blue fg:color_bright_white)[](color_blue)"
error_symbol = "[ ](fg:color_black bg:color_red)[✖](bg:color_red fg:color_bright_white)[](color_red)"
vimcmd_symbol = "[ ](fg:color_black bg:color_white)[❮](bg:color_white fg:color_bright_white)[](color_white)"

# ------------------------------------------------------------------------



########################
##### Right Prompt #####
########################

[memory_usage]  # https://starship.rs/config/#memory-usage
format = '[](color_red)[$symbol ${ram_pct}( | ${swap_pct})]($style)[](color_red)'
disabled = false
threshold = -1
symbol = "󰧑"
style = 'bg:color_red fg:color_bright_white'

[time]  # https://starship.rs/config/#time
disabled = false
time_format = "%I:%M%P"
style = "bg:color_white fg:color_black"
format = '[](color_white)[ $time]($style)[](color_white)'

[cmd_duration]  # https://starship.rs/config/#command-duration
format = '[](color_blue)[$duration]($style)[](color_blue)'
style = 'fg:color_bright_white bg:color_blue'
show_milliseconds = true
min_time = 0
