# Starship configuration     https://starship.rs/config/
# Nerd font icons (useful)   https://www.nerdfonts.com/cheat-sheet

format = """
$fill\
$line_break\
$character"""

[fill]
symbol = '─'

# -----------------------------------------------

[character]
success_symbol = '[](blue)'
error_symbol = '[](red)'
vimcmd_symbol = '[](green)'


