#!/bin/bash

export BASH_IT="$USER_BUILDS_HOME/bash_it" # Path to the bash it configuration
export BASH_IT_THEME='oh-my-posh'          # Lock and Load a custom theme file, location: /.bash_it/themes/

# THEME_CHECK_SUDO='true'                     # Some themes can check every prompt to show whether `sudo` has a current token or not.
# export BASH_IT_REMOTE='bash-it'             # (Advanced): Name of bash-it remote repo cloned with a remote other than origin.
# export BASH_IT_DEVELOPMENT_BRANCH='master'  # (Advanced): Name of bash-it main development branch if changed.

export GIT_HOSTING='git@git.domain.com' # Your place for hosting Git repos. I use this for private repos.
unset MAILCHECK                         # Don't check mail when opening terminal.
export IRC_CLIENT='irssi'               # Change this to your console based IRC client of choice.
export TODO="t"                         # Set this to the command you use for todo.txt-cli.
#BASH_IT_PROJECT_PATHS="${HOME}/Projects:/Volumes/work/src" # Set this to the location of your work or project folders.

export SCM_CHECK=false # Set this to false to turn off version control status checking within the prompt for all themes
#export SCM_GIT_GITSTATUS_DIR="$HOME/gitstatus" # Set to actual location of gitstatus directory if installed
#export GITSTATUS_NUM_THREADS=8                 # per default gitstatus uses 2 times as many threads as CPU cores, you can change this here if you must

# Set Xterm/screen/Tmux title with only a short hostname.
# Uncomment this (or set SHORT_HOSTNAME to something else),
# Will otherwise fall back on $HOSTNAME.
#export SHORT_HOSTNAME=$(hostname -s)

# Set Xterm/screen/Tmux title with only a short username.
# Uncomment this (or set SHORT_USER to something else),
# Will otherwise fall back on $USER.
#export SHORT_USER=${USER:0:8}

# If your theme use command duration, uncomment this to
# enable display of last command duration.
#export BASH_IT_COMMAND_DURATION=true
# You can choose the minimum time in seconds before
# command duration is displayed.
#export COMMAND_DURATION_MIN_SECONDS=1

# Set Xterm/screen/Tmux title with shortened command and directory.
# Uncomment this to set.
#export SHORT_TERM_LINE=true

# Set vcprompt executable path for scm advance info in prompt (demula theme)
# https://github.com/djl/vcprompt
#export VCPROMPT_EXECUTABLE=~/.vcprompt/bin/vcprompt

# (Advanced): Uncomment this to make Bash-it reload itself automatically
# after enabling or disabling aliases, plugins, and completions.
# export BASH_IT_AUTOMATIC_RELOAD_AFTER_CONFIG_CHANGE=1

# Uncomment this to make Bash-it create alias reload.
# export BASH_IT_RELOAD_LEGACY=1

# Load Bash It
source "$BASH_IT"/bash_it.sh
