#!/bin/bash

[[ -f $HOME/.config/bash/bashrc ]] && source $HOME/.config/bash/bashrc

# Difference between bash startup files: https://superuser.com/questions/183870/difference-between-bashrc-and-bash-profile
# How to add a PATH: https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path
