#!/usr/bin/env bash
# bashrc > interactive non-login

# If not running interactively, don't do anything
case $- in
*i*) ;;
*) return ;;
esac

[[ -f "$HOME/.config/scripts/xdg.sh" ]] && source "$HOME/.config/scripts/xdg.sh"
[[ -f $XDG_CONFIG_HOME/bash/bash_it ]] && source $XDG_CONFIG_HOME/bash/bash_it

# --- POSIX startup files ---
for setup_script in $USER_SCRIPTS_HOME/setup/*.sh; do
  source $setup_script
done

# --- Bash startup files ---
for bash_setup_file in $USER_SHELL_HOME/setup/*.bash; do
  source $bash_setup_file
done

# --- POSIX plugin files ---
for sh_plugin_file in $USER_SCRIPTS_HOME/plugins/*.sh; do
  source $sh_plugin_file
done

# --- Bash plugin files ---
for bash_plugin_file in $USER_SHELL_HOME/plugins/*.sh; do
  source $bash_plugin_file
done

# # Run different shell commands for login/non-login shells
# if shopt -q login-shell; then
# # login-shell code (or use .bash_logout file)
# else
# # non-login code (e.g. `trap '. ~/.bash_logout' EXIT`)
# fi
